import SwiftUI
import PDFKit

@MainActor
final class PDFExportService {

    static func generateSeatingPDF(plan: SeatingPlan) -> Data? {
        let pageWidth: CGFloat = 612  // Letter
        let pageHeight: CGFloat = 792
        let margin: CGFloat = 40

        let renderer = UIGraphicsPDFRenderer(bounds: CGRect(x: 0, y: 0, width: pageWidth, height: pageHeight))

        let data = renderer.pdfData { context in
            // PAGE 1: Cover
            context.beginPage()
            drawCoverPage(context: context.cgContext, plan: plan, pageWidth: pageWidth, pageHeight: pageHeight, margin: margin)

            // PAGE 2+: Table assignments
            let tablesPerPage = 4
            let tableChunks = stride(from: 0, to: plan.tables.count, by: tablesPerPage).map {
                Array(plan.tables[$0..<min($0 + tablesPerPage, plan.tables.count)])
            }

            for chunk in tableChunks {
                context.beginPage()
                drawTablePage(context: context.cgContext, tables: chunk, guests: plan.guests, plan: plan, pageWidth: pageWidth, pageHeight: pageHeight, margin: margin)
            }
        }

        return data
    }

    private static func drawCoverPage(context: CGContext, plan: SeatingPlan, pageWidth: CGFloat, pageHeight: CGFloat, margin: CGFloat) {
        let goldColor = UIColor(red: 201/255, green: 169/255, blue: 97/255, alpha: 1)
        let charcoalColor = UIColor(red: 45/255, green: 45/255, blue: 45/255, alpha: 1)
        let warmColor = UIColor(red: 139/255, green: 134/255, blue: 128/255, alpha: 1)

        // Title
        let titleAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 36, weight: .medium),
            .foregroundColor: charcoalColor
        ]
        let title = NSString(string: plan.name)
        let titleSize = title.size(withAttributes: titleAttrs)
        title.draw(at: CGPoint(x: (pageWidth - titleSize.width) / 2, y: pageHeight * 0.3), withAttributes: titleAttrs)

        // Subtitle
        let subtitleAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 18, weight: .regular),
            .foregroundColor: warmColor
        ]
        let subtitle = NSString(string: "Seating Arrangement")
        let subSize = subtitle.size(withAttributes: subtitleAttrs)
        subtitle.draw(at: CGPoint(x: (pageWidth - subSize.width) / 2, y: pageHeight * 0.3 + 50), withAttributes: subtitleAttrs)

        // Date & venue
        var detailY = pageHeight * 0.3 + 90
        let detailAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 14),
            .foregroundColor: warmColor
        ]

        if let date = plan.eventDate {
            let dateFormatter = DateFormatter()
            dateFormatter.dateStyle = .long
            let dateStr = NSString(string: dateFormatter.string(from: date))
            let dateSize = dateStr.size(withAttributes: detailAttrs)
            dateStr.draw(at: CGPoint(x: (pageWidth - dateSize.width) / 2, y: detailY), withAttributes: detailAttrs)
            detailY += 24
        }

        if let venue = plan.venue {
            let venueStr = NSString(string: venue)
            let venueSize = venueStr.size(withAttributes: detailAttrs)
            venueStr.draw(at: CGPoint(x: (pageWidth - venueSize.width) / 2, y: detailY), withAttributes: detailAttrs)
            detailY += 24
        }

        // Stats
        let statsY = pageHeight * 0.55
        let statsAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 28, weight: .medium),
            .foregroundColor: goldColor
        ]
        let labelAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 11, weight: .semibold),
            .foregroundColor: warmColor
        ]

        let stats = [
            ("\(plan.guests.count)", "GUESTS"),
            ("\(plan.tables.count)", "TABLES"),
            ("\(plan.tables.reduce(0) { $0 + $1.seats })", "SEATS")
        ]

        let statSpacing = pageWidth / CGFloat(stats.count + 1)
        for (i, stat) in stats.enumerated() {
            let x = statSpacing * CGFloat(i + 1)
            let numStr = NSString(string: stat.0)
            let numSize = numStr.size(withAttributes: statsAttrs)
            numStr.draw(at: CGPoint(x: x - numSize.width / 2, y: statsY), withAttributes: statsAttrs)

            let labStr = NSString(string: stat.1)
            let labSize = labStr.size(withAttributes: labelAttrs)
            labStr.draw(at: CGPoint(x: x - labSize.width / 2, y: statsY + 36), withAttributes: labelAttrs)
        }

        // Footer
        let footerAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 10),
            .foregroundColor: warmColor
        ]
        let footer = NSString(string: "Generated by Seatbee · seatbee.app")
        let footerSize = footer.size(withAttributes: footerAttrs)
        footer.draw(at: CGPoint(x: (pageWidth - footerSize.width) / 2, y: pageHeight - margin - 20), withAttributes: footerAttrs)
    }

    private static func drawTablePage(context: CGContext, tables: [SeatTable], guests: [Guest], plan: SeatingPlan, pageWidth: CGFloat, pageHeight: CGFloat, margin: CGFloat) {
        let charcoalColor = UIColor(red: 45/255, green: 45/255, blue: 45/255, alpha: 1)
        let goldColor = UIColor(red: 201/255, green: 169/255, blue: 97/255, alpha: 1)
        let warmColor = UIColor(red: 139/255, green: 134/255, blue: 128/255, alpha: 1)
        let ivoryColor = UIColor(red: 250/255, green: 246/255, blue: 236/255, alpha: 1)

        // Header
        let headerAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 12, weight: .semibold),
            .foregroundColor: warmColor
        ]
        let header = NSString(string: "SEATING ASSIGNMENTS — \(plan.name.uppercased())")
        header.draw(at: CGPoint(x: margin, y: margin), withAttributes: headerAttrs)

        // Draw tables in 2-column layout
        let colWidth = (pageWidth - margin * 3) / 2
        var y = margin + 40

        for (i, table) in tables.enumerated() {
            let col = CGFloat(i % 2)
            let x = margin + col * (colWidth + margin)

            if i > 0 && i % 2 == 0 {
                y += 180
            }

            // Table card background
            let cardRect = CGRect(x: x, y: y, width: colWidth, height: 160)
            context.setFillColor(ivoryColor.cgColor)
            let path = UIBezierPath(roundedRect: cardRect, cornerRadius: 8)
            context.addPath(path.cgPath)
            context.fillPath()

            // Table name
            let nameAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 16, weight: .semibold),
                .foregroundColor: charcoalColor
            ]
            NSString(string: table.name).draw(at: CGPoint(x: x + 12, y: y + 10), withAttributes: nameAttrs)

            // Seat info
            let infoAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 10),
                .foregroundColor: warmColor
            ]
            NSString(string: "\(table.type.rawValue) · \(table.seats) seats").draw(at: CGPoint(x: x + 12, y: y + 30), withAttributes: infoAttrs)

            // Guest names
            let guestAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 11),
                .foregroundColor: charcoalColor
            ]
            let dietaryAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 9),
                .foregroundColor: goldColor
            ]

            var guestY = y + 50
            for seatIdx in 0..<table.seats {
                if guestY > y + 145 { break }
                let guestId = table.assignments.first { $0.value == seatIdx }?.key
                let guest = guestId.flatMap { gId in guests.first { $0.id == gId } }

                let seatLabel = "\(seatIdx + 1). "
                let guestName = guest?.displayName ?? "—"

                NSString(string: seatLabel + guestName).draw(at: CGPoint(x: x + 14, y: guestY), withAttributes: guestAttrs)

                if let dietary = guest?.dietary {
                    NSString(string: dietary).draw(at: CGPoint(x: x + colWidth - 60, y: guestY + 1), withAttributes: dietaryAttrs)
                }

                guestY += 16
            }
        }
    }

    static func sharePDF(plan: SeatingPlan) {
        guard let data = generateSeatingPDF(plan: plan) else { return }

        let tempURL = FileManager.default.temporaryDirectory.appendingPathComponent("\(plan.name) Seating.pdf")
        try? data.write(to: tempURL)
        shareFile(tempURL)
    }

    // MARK: - Place Cards PDF

    static func generatePlaceCards(plan: SeatingPlan) -> Data? {
        let cardWidth: CGFloat = 252  // 3.5 inches
        let cardHeight: CGFloat = 180 // 2.5 inches
        let pageWidth: CGFloat = 612
        let pageHeight: CGFloat = 792
        let cols = 2
        let rows = 4
        let marginX: CGFloat = (pageWidth - CGFloat(cols) * cardWidth) / CGFloat(cols + 1)
        let marginY: CGFloat = (pageHeight - CGFloat(rows) * cardHeight) / CGFloat(rows + 1)

        let goldColor = UIColor(red: 201/255, green: 169/255, blue: 97/255, alpha: 1)
        let charcoalColor = UIColor(red: 45/255, green: 45/255, blue: 45/255, alpha: 1)
        let warmColor = UIColor(red: 139/255, green: 134/255, blue: 128/255, alpha: 1)

        // Collect all seated guests
        var seatedGuests: [(guest: Guest, table: SeatTable, seat: Int)] = []
        for table in plan.tables {
            for (guestId, seatIdx) in table.assignments {
                if let guest = plan.guests.first(where: { $0.id == guestId }) {
                    seatedGuests.append((guest, table, seatIdx))
                }
            }
        }
        seatedGuests.sort { $0.guest.displayName < $1.guest.displayName }

        let cardsPerPage = cols * rows
        let renderer = UIGraphicsPDFRenderer(bounds: CGRect(x: 0, y: 0, width: pageWidth, height: pageHeight))

        return renderer.pdfData { context in
            let chunks = stride(from: 0, to: seatedGuests.count, by: cardsPerPage).map {
                Array(seatedGuests[$0..<min($0 + cardsPerPage, seatedGuests.count)])
            }

            for chunk in chunks {
                context.beginPage()
                for (i, entry) in chunk.enumerated() {
                    let col = i % cols
                    let row = i / cols
                    let x = marginX + CGFloat(col) * (cardWidth + marginX)
                    let y = marginY + CGFloat(row) * (cardHeight + marginY)

                    // Card border
                    let cardRect = CGRect(x: x, y: y, width: cardWidth, height: cardHeight)
                    context.cgContext.setStrokeColor(goldColor.cgColor)
                    context.cgContext.setLineWidth(1)
                    context.cgContext.addRect(cardRect)
                    context.cgContext.strokePath()

                    // Guest name
                    let nameAttrs: [NSAttributedString.Key: Any] = [
                        .font: UIFont.systemFont(ofSize: 18, weight: .medium),
                        .foregroundColor: charcoalColor
                    ]
                    let name = NSString(string: entry.guest.displayName)
                    let nameSize = name.size(withAttributes: nameAttrs)
                    name.draw(at: CGPoint(x: x + (cardWidth - nameSize.width) / 2, y: y + 50), withAttributes: nameAttrs)

                    // Table assignment
                    let tableAttrs: [NSAttributedString.Key: Any] = [
                        .font: UIFont.systemFont(ofSize: 12),
                        .foregroundColor: goldColor
                    ]
                    let tableStr = NSString(string: "\(entry.table.name) · Seat \(entry.seat + 1)")
                    let tableSize = tableStr.size(withAttributes: tableAttrs)
                    tableStr.draw(at: CGPoint(x: x + (cardWidth - tableSize.width) / 2, y: y + 80), withAttributes: tableAttrs)

                    // Dietary note
                    if let dietary = entry.guest.dietary {
                        let dietAttrs: [NSAttributedString.Key: Any] = [
                            .font: UIFont.systemFont(ofSize: 10),
                            .foregroundColor: warmColor
                        ]
                        let dietStr = NSString(string: dietary)
                        let dietSize = dietStr.size(withAttributes: dietAttrs)
                        dietStr.draw(at: CGPoint(x: x + (cardWidth - dietSize.width) / 2, y: y + 110), withAttributes: dietAttrs)
                    }
                }
            }
        }
    }

    static func sharePlaceCards(plan: SeatingPlan) {
        guard let data = generatePlaceCards(plan: plan) else { return }
        let tempURL = FileManager.default.temporaryDirectory.appendingPathComponent("\(plan.name) Place Cards.pdf")
        try? data.write(to: tempURL)
        shareFile(tempURL)
    }

    // MARK: - Social Image

    @MainActor
    static func generateSocialImage(plan: SeatingPlan) -> UIImage? {
        let width: CGFloat = 1080
        let height: CGFloat = 1080

        let renderer = UIGraphicsImageRenderer(size: CGSize(width: width, height: height))
        return renderer.image { context in
            let ctx = context.cgContext
            let goldColor = UIColor(red: 201/255, green: 169/255, blue: 97/255, alpha: 1)
            let ivoryColor = UIColor(red: 255/255, green: 254/255, blue: 249/255, alpha: 1)
            let charcoalColor = UIColor(red: 45/255, green: 45/255, blue: 45/255, alpha: 1)

            // Background
            ctx.setFillColor(ivoryColor.cgColor)
            ctx.fill(CGRect(x: 0, y: 0, width: width, height: height))

            // Title
            let titleAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 48, weight: .medium),
                .foregroundColor: charcoalColor
            ]
            let title = NSString(string: plan.name)
            let titleSize = title.size(withAttributes: titleAttrs)
            title.draw(at: CGPoint(x: (width - titleSize.width) / 2, y: 120), withAttributes: titleAttrs)

            // Subtitle
            let subAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 24),
                .foregroundColor: goldColor
            ]
            let sub = NSString(string: "Seating Arrangement")
            let subSize = sub.size(withAttributes: subAttrs)
            sub.draw(at: CGPoint(x: (width - subSize.width) / 2, y: 180), withAttributes: subAttrs)

            // Stats
            let statsY: CGFloat = 280
            let statAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 64, weight: .medium),
                .foregroundColor: goldColor
            ]
            let labelAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 18, weight: .semibold),
                .foregroundColor: charcoalColor
            ]

            let stats = [("\(plan.guests.count)", "GUESTS"), ("\(plan.tables.count)", "TABLES")]
            for (i, stat) in stats.enumerated() {
                let x = width / 3 * CGFloat(i + 1)
                let numStr = NSString(string: stat.0)
                let numSize = numStr.size(withAttributes: statAttrs)
                numStr.draw(at: CGPoint(x: x - numSize.width / 2, y: statsY), withAttributes: statAttrs)
                let labStr = NSString(string: stat.1)
                let labSize = labStr.size(withAttributes: labelAttrs)
                labStr.draw(at: CGPoint(x: x - labSize.width / 2, y: statsY + 72), withAttributes: labelAttrs)
            }

            // Footer
            let footerAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 16),
                .foregroundColor: UIColor.gray
            ]
            let footer = NSString(string: "Made with Seatbee · seatbee.app")
            let footerSize = footer.size(withAttributes: footerAttrs)
            footer.draw(at: CGPoint(x: (width - footerSize.width) / 2, y: height - 60), withAttributes: footerAttrs)
        }
    }

    static func shareSocialImage(plan: SeatingPlan) {
        guard let image = generateSocialImage(plan: plan),
              let data = image.pngData() else { return }
        let tempURL = FileManager.default.temporaryDirectory.appendingPathComponent("\(plan.name) Seating.png")
        try? data.write(to: tempURL)
        shareFile(tempURL)
    }

    // MARK: - CSV exports (web parity)
    //
    // Mirrors web's `expGuestCSV` and `expTableCSV`. Same column order and
    // semantics so a CSV produced on iOS opens cleanly in the same spreadsheet
    // template a web user would use.

    static func shareGuestListCSV(plan: SeatingPlan) {
        let csv = generateGuestCSV(plan: plan)
        let url = writeTempFile(csv, name: "\(safeFilename(plan.name)) Guests.csv")
        shareFile(url)
    }

    static func shareTablesCSV(plan: SeatingPlan) {
        let csv = generateTablesCSV(plan: plan)
        let url = writeTempFile(csv, name: "\(safeFilename(plan.name)) Tables.csv")
        shareFile(url)
    }

    private static func generateGuestCSV(plan: SeatingPlan) -> String {
        // Build a guest → (table, seat) lookup so we don't scan tables N times.
        var seatByGuest: [String: (table: SeatTable, seat: Int)] = [:]
        for table in plan.tables {
            for (guestId, seatIndex) in table.assignments {
                seatByGuest[guestId] = (table, seatIndex)
            }
        }

        let header = [
            "Name", "Email", "Side", "Table", "Seat",
            "RSVP", "Meal", "Dietary", "Categories",
            "VIP", "Child", "High Chair", "Notes"
        ]
        var rows: [[String]] = [header]
        for g in plan.guests {
            let assignment = seatByGuest[g.id]
            let categoryNames = g.categories.compactMap { id -> String? in
                guard let raw = plan.rawCategories else { return id }
                let entry = raw.first { ($0["id"]?.value as? String) == id }
                return (entry?["name"]?.value as? String) ?? id
            }.joined(separator: "; ")

            rows.append([
                g.displayName,
                g.email ?? "",
                g.side.rawValue,
                assignment?.table.name ?? "",
                assignment.map { String($0.seat + 1) } ?? "",
                g.rsvp.rawValue,
                g.meal ?? "",
                g.dietary ?? "",
                categoryNames,
                g.vip ? "yes" : "",
                (g.isChild == true) ? "yes" : "",
                (g.highChair == true) ? "yes" : "",
                g.notes ?? "",
            ])
        }
        return csvString(rows)
    }

    private static func generateTablesCSV(plan: SeatingPlan) -> String {
        let header = [
            "Table", "Type", "Capacity", "Seated", "Locked",
            "Guests", "Meal breakdown", "Dietary needs", "High chairs"
        ]
        var rows: [[String]] = [header]

        let guestsById = Dictionary(uniqueKeysWithValues: plan.guests.map { ($0.id, $0) })

        for table in plan.tables {
            let tableGuests = table.assignments.keys.compactMap { guestsById[$0] }
            let names = tableGuests.map { $0.displayName }.joined(separator: "; ")

            // Meal counts (web parity: `Beef: 3, Chicken: 2`).
            var mealCounts: [String: Int] = [:]
            for g in tableGuests {
                if let m = g.meal, !m.isEmpty {
                    mealCounts[m, default: 0] += 1
                }
            }
            let mealBreakdown = mealCounts
                .sorted { $0.key < $1.key }
                .map { "\($0.key): \($0.value)" }
                .joined(separator: ", ")

            // Dietary needs — count guests with non-empty dietary or any tag.
            let dietaryCount = tableGuests.filter {
                !($0.dietary ?? "").isEmpty || !(($0.dietaryTags ?? []).isEmpty)
            }.count

            let highChairCount = tableGuests.filter { $0.highChair == true }.count

            rows.append([
                table.name,
                table.type.rawValue,
                String(table.seats),
                String(table.assignments.count),
                (table.locked == true) ? "yes" : "",
                names,
                mealBreakdown,
                dietaryCount > 0 ? String(dietaryCount) : "",
                highChairCount > 0 ? String(highChairCount) : "",
            ])
        }
        return csvString(rows)
    }

    /// RFC 4180 CSV — wrap any field containing `,`, `"`, or newline in
    /// double quotes; double-up internal `"`. Matches Excel/Numbers parsing.
    private static func csvString(_ rows: [[String]]) -> String {
        rows.map { row in
            row.map { cell in
                if cell.contains(",") || cell.contains("\"") || cell.contains("\n") {
                    let escaped = cell.replacingOccurrences(of: "\"", with: "\"\"")
                    return "\"\(escaped)\""
                }
                return cell
            }
            .joined(separator: ",")
        }
        .joined(separator: "\r\n")
    }

    private static func writeTempFile(_ contents: String, name: String) -> URL {
        let url = FileManager.default.temporaryDirectory.appendingPathComponent(name)
        try? contents.write(to: url, atomically: true, encoding: .utf8)
        return url
    }

    private static func safeFilename(_ name: String) -> String {
        let invalid = CharacterSet(charactersIn: "/\\?%*|\"<>:")
        return name.components(separatedBy: invalid).joined(separator: "-")
    }

    // MARK: - Share Helper

    private static func shareFile(_ url: URL) {
        let activityVC = UIActivityViewController(
            activityItems: [url],
            applicationActivities: nil
        )
        if let windowScene = UIApplication.shared.connectedScenes.first as? UIWindowScene,
           let rootVC = windowScene.windows.first?.rootViewController {
            rootVC.present(activityVC, animated: true)
        }
    }
}
