import SwiftUI
import PDFKit

@MainActor
final class PDFExportService {

    static func generateSeatingPDF(plan: SeatingPlan) -> Data? {
        let pageWidth: CGFloat = 612  // Letter
        let pageHeight: CGFloat = 792
        let margin: CGFloat = 40

        let renderer = UIGraphicsPDFRenderer(bounds: CGRect(x: 0, y: 0, width: pageWidth, height: pageHeight))

        let data = renderer.pdfData { context in
            // PAGE 1: Cover
            context.beginPage()
            drawCoverPage(context: context.cgContext, plan: plan, pageWidth: pageWidth, pageHeight: pageHeight, margin: margin)

            // PAGE 2+: Table assignments
            let tablesPerPage = 4
            let tableChunks = stride(from: 0, to: plan.tables.count, by: tablesPerPage).map {
                Array(plan.tables[$0..<min($0 + tablesPerPage, plan.tables.count)])
            }

            for chunk in tableChunks {
                context.beginPage()
                drawTablePage(context: context.cgContext, tables: chunk, guests: plan.guests, plan: plan, pageWidth: pageWidth, pageHeight: pageHeight, margin: margin)
            }
        }

        return data
    }

    private static func drawCoverPage(context: CGContext, plan: SeatingPlan, pageWidth: CGFloat, pageHeight: CGFloat, margin: CGFloat) {
        let goldColor = UIColor(red: 201/255, green: 169/255, blue: 97/255, alpha: 1)
        let charcoalColor = UIColor(red: 45/255, green: 45/255, blue: 45/255, alpha: 1)
        let warmColor = UIColor(red: 139/255, green: 134/255, blue: 128/255, alpha: 1)

        // Title
        let titleAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 36, weight: .medium),
            .foregroundColor: charcoalColor
        ]
        let title = NSString(string: plan.name)
        let titleSize = title.size(withAttributes: titleAttrs)
        title.draw(at: CGPoint(x: (pageWidth - titleSize.width) / 2, y: pageHeight * 0.3), withAttributes: titleAttrs)

        // Subtitle
        let subtitleAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 18, weight: .regular),
            .foregroundColor: warmColor
        ]
        let subtitle = NSString(string: "Seating Arrangement")
        let subSize = subtitle.size(withAttributes: subtitleAttrs)
        subtitle.draw(at: CGPoint(x: (pageWidth - subSize.width) / 2, y: pageHeight * 0.3 + 50), withAttributes: subtitleAttrs)

        // Date & venue
        var detailY = pageHeight * 0.3 + 90
        let detailAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 14),
            .foregroundColor: warmColor
        ]

        if let date = plan.eventDate {
            let dateFormatter = DateFormatter()
            dateFormatter.dateStyle = .long
            let dateStr = NSString(string: dateFormatter.string(from: date))
            let dateSize = dateStr.size(withAttributes: detailAttrs)
            dateStr.draw(at: CGPoint(x: (pageWidth - dateSize.width) / 2, y: detailY), withAttributes: detailAttrs)
            detailY += 24
        }

        if let venue = plan.venue {
            let venueStr = NSString(string: venue)
            let venueSize = venueStr.size(withAttributes: detailAttrs)
            venueStr.draw(at: CGPoint(x: (pageWidth - venueSize.width) / 2, y: detailY), withAttributes: detailAttrs)
            detailY += 24
        }

        // Stats
        let statsY = pageHeight * 0.55
        let statsAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 28, weight: .medium),
            .foregroundColor: goldColor
        ]
        let labelAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 11, weight: .semibold),
            .foregroundColor: warmColor
        ]

        let stats = [
            ("\(plan.guests.count)", "GUESTS"),
            ("\(plan.tables.count)", "TABLES"),
            ("\(plan.tables.reduce(0) { $0 + $1.seats })", "SEATS")
        ]

        let statSpacing = pageWidth / CGFloat(stats.count + 1)
        for (i, stat) in stats.enumerated() {
            let x = statSpacing * CGFloat(i + 1)
            let numStr = NSString(string: stat.0)
            let numSize = numStr.size(withAttributes: statsAttrs)
            numStr.draw(at: CGPoint(x: x - numSize.width / 2, y: statsY), withAttributes: statsAttrs)

            let labStr = NSString(string: stat.1)
            let labSize = labStr.size(withAttributes: labelAttrs)
            labStr.draw(at: CGPoint(x: x - labSize.width / 2, y: statsY + 36), withAttributes: labelAttrs)
        }

        // Footer
        let footerAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 10),
            .foregroundColor: warmColor
        ]
        let footer = NSString(string: "Generated by Seatbee · seatbee.app")
        let footerSize = footer.size(withAttributes: footerAttrs)
        footer.draw(at: CGPoint(x: (pageWidth - footerSize.width) / 2, y: pageHeight - margin - 20), withAttributes: footerAttrs)
    }

    private static func drawTablePage(context: CGContext, tables: [SeatTable], guests: [Guest], plan: SeatingPlan, pageWidth: CGFloat, pageHeight: CGFloat, margin: CGFloat) {
        let charcoalColor = UIColor(red: 45/255, green: 45/255, blue: 45/255, alpha: 1)
        let goldColor = UIColor(red: 201/255, green: 169/255, blue: 97/255, alpha: 1)
        let warmColor = UIColor(red: 139/255, green: 134/255, blue: 128/255, alpha: 1)
        let ivoryColor = UIColor(red: 250/255, green: 246/255, blue: 236/255, alpha: 1)

        // Header
        let headerAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 12, weight: .semibold),
            .foregroundColor: warmColor
        ]
        let header = NSString(string: "SEATING ASSIGNMENTS — \(plan.name.uppercased())")
        header.draw(at: CGPoint(x: margin, y: margin), withAttributes: headerAttrs)

        // Draw tables in 2-column layout
        let colWidth = (pageWidth - margin * 3) / 2
        var y = margin + 40

        for (i, table) in tables.enumerated() {
            let col = CGFloat(i % 2)
            let x = margin + col * (colWidth + margin)

            if i > 0 && i % 2 == 0 {
                y += 180
            }

            // Table card background
            let cardRect = CGRect(x: x, y: y, width: colWidth, height: 160)
            context.setFillColor(ivoryColor.cgColor)
            let path = UIBezierPath(roundedRect: cardRect, cornerRadius: 8)
            context.addPath(path.cgPath)
            context.fillPath()

            // Table name
            let nameAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 16, weight: .semibold),
                .foregroundColor: charcoalColor
            ]
            NSString(string: table.name).draw(at: CGPoint(x: x + 12, y: y + 10), withAttributes: nameAttrs)

            // Seat info
            let infoAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 10),
                .foregroundColor: warmColor
            ]
            NSString(string: "\(table.type.rawValue) · \(table.seats) seats").draw(at: CGPoint(x: x + 12, y: y + 30), withAttributes: infoAttrs)

            // Guest names
            let guestAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 11),
                .foregroundColor: charcoalColor
            ]
            let dietaryAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 9),
                .foregroundColor: goldColor
            ]

            var guestY = y + 50
            for seatIdx in 0..<table.seats {
                if guestY > y + 145 { break }
                let guestId = table.assignments.first { $0.value == seatIdx }?.key
                let guest = guestId.flatMap { gId in guests.first { $0.id == gId } }

                let seatLabel = "\(seatIdx + 1). "
                let guestName = guest?.displayName ?? "—"

                NSString(string: seatLabel + guestName).draw(at: CGPoint(x: x + 14, y: guestY), withAttributes: guestAttrs)

                if let dietary = guest?.dietary {
                    NSString(string: dietary).draw(at: CGPoint(x: x + colWidth - 60, y: guestY + 1), withAttributes: dietaryAttrs)
                }

                guestY += 16
            }
        }
    }

    static func sharePDF(plan: SeatingPlan) {
        guard let data = generateSeatingPDF(plan: plan) else { return }

        let tempURL = FileManager.default.temporaryDirectory.appendingPathComponent("\(plan.name) Seating.pdf")
        try? data.write(to: tempURL)
        shareFile(tempURL)
    }

    // MARK: - Place Cards PDF

    static func generatePlaceCards(plan: SeatingPlan) -> Data? {
        let cardWidth: CGFloat = 252  // 3.5 inches
        let cardHeight: CGFloat = 180 // 2.5 inches
        let pageWidth: CGFloat = 612
        let pageHeight: CGFloat = 792
        let cols = 2
        let rows = 4
        let marginX: CGFloat = (pageWidth - CGFloat(cols) * cardWidth) / CGFloat(cols + 1)
        let marginY: CGFloat = (pageHeight - CGFloat(rows) * cardHeight) / CGFloat(rows + 1)

        let goldColor = UIColor(red: 201/255, green: 169/255, blue: 97/255, alpha: 1)
        let charcoalColor = UIColor(red: 45/255, green: 45/255, blue: 45/255, alpha: 1)
        let warmColor = UIColor(red: 139/255, green: 134/255, blue: 128/255, alpha: 1)

        // Collect all seated guests
        var seatedGuests: [(guest: Guest, table: SeatTable, seat: Int)] = []
        for table in plan.tables {
            for (guestId, seatIdx) in table.assignments {
                if let guest = plan.guests.first(where: { $0.id == guestId }) {
                    seatedGuests.append((guest, table, seatIdx))
                }
            }
        }
        seatedGuests.sort { $0.guest.displayName < $1.guest.displayName }

        let cardsPerPage = cols * rows
        let renderer = UIGraphicsPDFRenderer(bounds: CGRect(x: 0, y: 0, width: pageWidth, height: pageHeight))

        return renderer.pdfData { context in
            let chunks = stride(from: 0, to: seatedGuests.count, by: cardsPerPage).map {
                Array(seatedGuests[$0..<min($0 + cardsPerPage, seatedGuests.count)])
            }

            for chunk in chunks {
                context.beginPage()
                for (i, entry) in chunk.enumerated() {
                    let col = i % cols
                    let row = i / cols
                    let x = marginX + CGFloat(col) * (cardWidth + marginX)
                    let y = marginY + CGFloat(row) * (cardHeight + marginY)

                    // Card border
                    let cardRect = CGRect(x: x, y: y, width: cardWidth, height: cardHeight)
                    context.cgContext.setStrokeColor(goldColor.cgColor)
                    context.cgContext.setLineWidth(1)
                    context.cgContext.addRect(cardRect)
                    context.cgContext.strokePath()

                    // Guest name
                    let nameAttrs: [NSAttributedString.Key: Any] = [
                        .font: UIFont.systemFont(ofSize: 18, weight: .medium),
                        .foregroundColor: charcoalColor
                    ]
                    let name = NSString(string: entry.guest.displayName)
                    let nameSize = name.size(withAttributes: nameAttrs)
                    name.draw(at: CGPoint(x: x + (cardWidth - nameSize.width) / 2, y: y + 50), withAttributes: nameAttrs)

                    // Table assignment
                    let tableAttrs: [NSAttributedString.Key: Any] = [
                        .font: UIFont.systemFont(ofSize: 12),
                        .foregroundColor: goldColor
                    ]
                    let tableStr = NSString(string: "\(entry.table.name) · Seat \(entry.seat + 1)")
                    let tableSize = tableStr.size(withAttributes: tableAttrs)
                    tableStr.draw(at: CGPoint(x: x + (cardWidth - tableSize.width) / 2, y: y + 80), withAttributes: tableAttrs)

                    // Dietary note
                    if let dietary = entry.guest.dietary {
                        let dietAttrs: [NSAttributedString.Key: Any] = [
                            .font: UIFont.systemFont(ofSize: 10),
                            .foregroundColor: warmColor
                        ]
                        let dietStr = NSString(string: dietary)
                        let dietSize = dietStr.size(withAttributes: dietAttrs)
                        dietStr.draw(at: CGPoint(x: x + (cardWidth - dietSize.width) / 2, y: y + 110), withAttributes: dietAttrs)
                    }
                }
            }
        }
    }

    static func sharePlaceCards(plan: SeatingPlan) {
        guard let data = generatePlaceCards(plan: plan) else { return }
        let tempURL = FileManager.default.temporaryDirectory.appendingPathComponent("\(plan.name) Place Cards.pdf")
        try? data.write(to: tempURL)
        shareFile(tempURL)
    }

    // MARK: - Social Image

    @MainActor
    static func generateSocialImage(plan: SeatingPlan) -> UIImage? {
        let width: CGFloat = 1080
        let height: CGFloat = 1080

        let renderer = UIGraphicsImageRenderer(size: CGSize(width: width, height: height))
        return renderer.image { context in
            let ctx = context.cgContext
            let goldColor = UIColor(red: 201/255, green: 169/255, blue: 97/255, alpha: 1)
            let ivoryColor = UIColor(red: 255/255, green: 254/255, blue: 249/255, alpha: 1)
            let charcoalColor = UIColor(red: 45/255, green: 45/255, blue: 45/255, alpha: 1)

            // Background
            ctx.setFillColor(ivoryColor.cgColor)
            ctx.fill(CGRect(x: 0, y: 0, width: width, height: height))

            // Title
            let titleAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 48, weight: .medium),
                .foregroundColor: charcoalColor
            ]
            let title = NSString(string: plan.name)
            let titleSize = title.size(withAttributes: titleAttrs)
            title.draw(at: CGPoint(x: (width - titleSize.width) / 2, y: 120), withAttributes: titleAttrs)

            // Subtitle
            let subAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 24),
                .foregroundColor: goldColor
            ]
            let sub = NSString(string: "Seating Arrangement")
            let subSize = sub.size(withAttributes: subAttrs)
            sub.draw(at: CGPoint(x: (width - subSize.width) / 2, y: 180), withAttributes: subAttrs)

            // Stats
            let statsY: CGFloat = 280
            let statAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 64, weight: .medium),
                .foregroundColor: goldColor
            ]
            let labelAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 18, weight: .semibold),
                .foregroundColor: charcoalColor
            ]

            let stats = [("\(plan.guests.count)", "GUESTS"), ("\(plan.tables.count)", "TABLES")]
            for (i, stat) in stats.enumerated() {
                let x = width / 3 * CGFloat(i + 1)
                let numStr = NSString(string: stat.0)
                let numSize = numStr.size(withAttributes: statAttrs)
                numStr.draw(at: CGPoint(x: x - numSize.width / 2, y: statsY), withAttributes: statAttrs)
                let labStr = NSString(string: stat.1)
                let labSize = labStr.size(withAttributes: labelAttrs)
                labStr.draw(at: CGPoint(x: x - labSize.width / 2, y: statsY + 72), withAttributes: labelAttrs)
            }

            // Footer
            let footerAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 16),
                .foregroundColor: UIColor.gray
            ]
            let footer = NSString(string: "Made with Seatbee · seatbee.app")
            let footerSize = footer.size(withAttributes: footerAttrs)
            footer.draw(at: CGPoint(x: (width - footerSize.width) / 2, y: height - 60), withAttributes: footerAttrs)
        }
    }

    static func shareSocialImage(plan: SeatingPlan) {
        guard let image = generateSocialImage(plan: plan),
              let data = image.pngData() else { return }
        let tempURL = FileManager.default.temporaryDirectory.appendingPathComponent("\(plan.name) Seating.png")
        try? data.write(to: tempURL)
        shareFile(tempURL)
    }

    // MARK: - CSV exports (web parity)
    //
    // Mirrors web's `expGuestCSV` and `expTableCSV`. Same column order and
    // semantics so a CSV produced on iOS opens cleanly in the same spreadsheet
    // template a web user would use.

    static func shareGuestListCSV(plan: SeatingPlan) {
        let csv = generateGuestCSV(plan: plan)
        // Web parity (App.jsx:14429): replace any non-alphanumeric with
        // _, suffix `_guests.csv`.
        let url = writeTempFile(csv, name: "\(csvSafeName(plan.name))_guests.csv")
        shareFile(url)
    }

    static func shareTablesCSV(plan: SeatingPlan) {
        let csv = generateTablesCSV(plan: plan)
        let url = writeTempFile(csv, name: "\(csvSafeName(plan.name))_tables.csv")
        shareFile(url)
    }

    /// Web parity (`(state.event?.name||'seating').replace(/[^a-z0-9]/gi,'_')`).
    /// Underscore-replaces any character that isn't `[A-Za-z0-9]`.
    private static func csvSafeName(_ name: String) -> String {
        let allowed = CharacterSet.alphanumerics
        let mapped = name.unicodeScalars.map { allowed.contains($0) ? Character($0) : "_" }
        let result = String(mapped)
        return result.isEmpty ? "seating" : result
    }

    private static func generateGuestCSV(plan: SeatingPlan) -> String {
        // Web parity (App.jsx expCSV ~14406). Column order, header
        // names, value formatting, and even the always-empty Seat
        // column all match exactly so caterers/vendors can't tell
        // which client produced the file.
        var seatByGuest: [String: SeatTable] = [:]
        for table in plan.tables {
            for guestId in table.assignments.keys {
                seatByGuest[guestId] = table
            }
        }

        // Resolve per-guest party member names from rawParties so the
        // Party column matches web's `partyNames` formatting (display
        // or first-name fallback, joined by '; ', excludes self).
        var partyMemberNames: [String: String] = [:]
        if let rawParties = plan.rawParties {
            let guestById = Dictionary(uniqueKeysWithValues: plan.guests.map { ($0.id, $0) })
            for partyDict in rawParties {
                guard let memberIds = partyDict["guestIds"]?.value as? [String] else { continue }
                let names = memberIds.map { id -> (gid: String, name: String) in
                    guard let g = guestById[id] else { return (id, "") }
                    let label = (g.display?.isEmpty == false) ? g.display!
                        : g.name.split(separator: " ").first.map(String.init) ?? ""
                    return (id, label)
                }
                for (gid, _) in names {
                    let others = names.filter { $0.gid != gid && !$0.name.isEmpty }
                                      .map(\.name)
                                      .joined(separator: "; ")
                    if !others.isEmpty { partyMemberNames[gid] = others }
                }
            }
        }

        let header = [
            "Guest Name", "Display Name", "RSVP", "Table", "Seat",
            "Meal", "Dietary", "Category", "Side", "VIP",
            "Child", "High Chair", "Party", "Email", "Phone", "Notes"
        ]
        var rows: [[String]] = [header]
        for g in plan.guests {
            let table = seatByGuest[g.id]
            let categoryNames = g.categories.compactMap { id -> String? in
                guard let raw = plan.rawCategories else { return id }
                let entry = raw.first { ($0["id"]?.value as? String) == id }
                return (entry?["name"]?.value as? String) ?? id
            }.joined(separator: "; ")

            // Web mapping: yes→Yes, no→No, pending→Maybe, else ''
            let rsvpLabel: String
            switch g.rsvp {
            case .yes:     rsvpLabel = "Yes"
            case .no:      rsvpLabel = "No"
            case .pending: rsvpLabel = "Maybe"
            default:       rsvpLabel = ""
            }

            rows.append([
                g.name,                                  // Guest Name (full)
                g.display ?? "",                          // Display Name
                rsvpLabel,                                // RSVP (capitalized)
                table?.name ?? "Unassigned",              // Table
                "",                                       // Seat (web leaves blank — App.jsx:14423)
                g.meal ?? "",                             // Meal
                g.dietary ?? "",                          // Dietary
                categoryNames,                            // Category (joined; matches web's `cats`)
                g.side.rawValue,                          // Side
                g.vip ? "Yes" : "",                       // VIP (capital Y, matches web)
                (g.isChild == true) ? "Yes" : "",         // Child
                (g.highChair == true) ? "Yes" : "",       // High Chair
                partyMemberNames[g.id] ?? "",             // Party (other member names)
                g.email ?? "",                            // Email
                "",                                       // Phone (iOS Guest model has no phone field)
                g.notes ?? "",                            // Notes
            ])
        }
        return csvString(rows)
    }

    /// Web parity (App.jsx getMealShort). Maps a guest's free-text
    /// meal to a normalised short label so meal columns aggregate
    /// cleanly. `Beef`/`Salmon`/`Chicken`/`Vegan` are the canonical
    /// shorts; anything else falls back to the first two words.
    private static func mealShort(_ raw: String?) -> String? {
        guard let raw, !raw.isEmpty else { return nil }
        let m = raw.lowercased()
        if m.contains("beef") || m.contains("tenderloin") { return "Beef" }
        if m.contains("salmon") || m.contains("prawn") || m.contains("fish") { return "Salmon" }
        if m.contains("chicken") { return "Chicken" }
        if m.contains("mushroom") || m.contains("quinoa") || m.contains("vegan") || m.contains("vegetarian") {
            return "Vegan"
        }
        return raw.split(separator: " ").prefix(2).joined(separator: " ")
    }

    private static func generateTablesCSV(plan: SeatingPlan) -> String {
        // Web parity (App.jsx expTableCSV ~14433). One column PER meal
        // type (Beef / Chicken / Salmon / Vegan / etc.) instead of a
        // single combined "Meal breakdown" column. Includes an
        // (Unassigned) row for guests with no table and a TOTALS row.
        let guestsById = Dictionary(uniqueKeysWithValues: plan.guests.map { ($0.id, $0) })
        let assignedIds = Set(plan.tables.flatMap { $0.assignments.keys })

        // Collect every meal short across SEATED guests, sorted alpha.
        var mealSet = Set<String>()
        for g in plan.guests where assignedIds.contains(g.id) {
            if let s = mealShort(g.meal) { mealSet.insert(s) }
        }
        let mealTypes = mealSet.sorted()
        let hasMeals = !mealTypes.isEmpty

        var header = ["Table", "Type", "Capacity", "Seated"]
        if hasMeals { header.append(contentsOf: mealTypes) }
        header.append(contentsOf: ["Dietary Needs", "High Chairs", "Guests"])

        var rows: [[String]] = [header]

        var totalSeated = 0
        var totalCapacity = 0
        var totalHighChairs = 0
        var totalMeals: [String: Int] = [:]
        for m in mealTypes { totalMeals[m] = 0 }
        var totalDietary: [String] = []

        for table in plan.tables {
            let tGuests = table.assignments.keys.compactMap { guestsById[$0] }
            let seated = tGuests.count
            totalSeated += seated
            totalCapacity += table.seats

            var mealCounts: [String: Int] = [:]
            for m in mealTypes { mealCounts[m] = 0 }
            for g in tGuests {
                if let s = mealShort(g.meal), mealCounts[s] != nil {
                    mealCounts[s, default: 0] += 1
                    totalMeals[s, default: 0] += 1
                }
            }

            let dietaryList = tGuests.compactMap { g -> String? in
                guard let d = g.dietary, !d.isEmpty else { return nil }
                return d
            }
            let dietarySummary = dietaryList.joined(separator: "; ")
            totalDietary.append(contentsOf: dietaryList)

            let highChairs = tGuests.filter { $0.highChair == true }.count
            totalHighChairs += highChairs

            // Web uses g.name (full) for the table's guest list, not
            // displayName.
            let names = tGuests.map { $0.name }.joined(separator: "; ")

            var row: [String] = [
                table.name,
                table.type.rawValue,
                String(table.seats),
                String(seated),
            ]
            if hasMeals {
                row.append(contentsOf: mealTypes.map { mealCounts[$0]! > 0 ? String(mealCounts[$0]!) : "" })
            }
            row.append(contentsOf: [
                dietarySummary,
                highChairs > 0 ? String(highChairs) : "",
                names,
            ])
            rows.append(row)
        }

        // (Unassigned) row — RSVP=no guests are excluded, matching web.
        let unassigned = plan.guests.filter {
            !assignedIds.contains($0.id) && $0.rsvp != .no
        }
        if !unassigned.isEmpty {
            var mealCounts: [String: Int] = [:]
            for m in mealTypes { mealCounts[m] = 0 }
            for g in unassigned {
                if let s = mealShort(g.meal), mealCounts[s] != nil {
                    mealCounts[s, default: 0] += 1
                    totalMeals[s, default: 0] += 1
                }
            }
            let dietaryList = unassigned.compactMap { g -> String? in
                guard let d = g.dietary, !d.isEmpty else { return nil }
                return d
            }
            let highChairs = unassigned.filter { $0.highChair == true }.count
            totalHighChairs += highChairs

            var row: [String] = ["(Unassigned)", "", "-", String(unassigned.count)]
            if hasMeals {
                row.append(contentsOf: mealTypes.map { mealCounts[$0]! > 0 ? String(mealCounts[$0]!) : "" })
            }
            row.append(contentsOf: [
                dietaryList.joined(separator: "; "),
                highChairs > 0 ? String(highChairs) : "",
                unassigned.map { $0.name }.joined(separator: "; "),
            ])
            rows.append(row)
        }

        // Blank separator + TOTALS row.
        rows.append([])
        var totals: [String] = ["TOTALS", "", String(totalCapacity), String(totalSeated + unassigned.count)]
        if hasMeals {
            totals.append(contentsOf: mealTypes.map { String(totalMeals[$0] ?? 0) })
        }
        totals.append(contentsOf: [
            "\(totalDietary.count) total",
            totalHighChairs > 0 ? String(totalHighChairs) : "",
            "",
        ])
        rows.append(totals)

        return csvString(rows)
    }

    /// Web-parity CSV (App.jsx ~14425): wraps EVERY field in double
    /// quotes (not just ones containing separators), doubles internal
    /// quotes, joins rows with `\n` (not CRLF). Excel + Numbers parse
    /// either format fine, but matching byte-for-byte means a vendor
    /// can't tell which client generated the file.
    private static func csvString(_ rows: [[String]]) -> String {
        rows.map { row in
            row.map { cell in
                let escaped = cell.replacingOccurrences(of: "\"", with: "\"\"")
                return "\"\(escaped)\""
            }
            .joined(separator: ",")
        }
        .joined(separator: "\n")
    }

    private static func writeTempFile(_ contents: String, name: String) -> URL {
        let url = FileManager.default.temporaryDirectory.appendingPathComponent(name)
        try? contents.write(to: url, atomically: true, encoding: .utf8)
        return url
    }

    private static func safeFilename(_ name: String) -> String {
        let invalid = CharacterSet(charactersIn: "/\\?%*|\"<>:")
        return name.components(separatedBy: invalid).joined(separator: "-")
    }

    // MARK: - Share Helper

    private static func shareFile(_ url: URL) {
        let activityVC = UIActivityViewController(
            activityItems: [url],
            applicationActivities: nil
        )
        if let windowScene = UIApplication.shared.connectedScenes.first as? UIWindowScene,
           let rootVC = windowScene.windows.first?.rootViewController {
            rootVC.present(activityVC, animated: true)
        }
    }
}
