import SwiftUI
import UniformTypeIdentifiers

// Brought to parity with the onboarding upload surface (web parity
// goal: same paste / template / CSV experience whether you land
// here from onboarding or from the Guests tab post-creation):
//   - File button now shows the same platform subtitle used in
//     onboarding (Joy, Zola, The Knot, Eventbrite, generic CSV).
//   - "Download CSV template" link below — picks the template
//     flavour from the active plan's event type (wedding /
//     celebration) and falls back to wedding when no plan is open.
//   - Paste textarea uses the same example as onboarding
//     ("Sarah Chen, vegetarian") instead of intimidating CSV
//     header copy. Auto-parses on every keystroke via the shared
//     `GuestCSVParser.parseFlexible` — no "Parse pasted text"
//     button needed.
//   - Same dietary-syntax tip line so users discover the inline
//     comma-separator pattern.
struct CSVImportSheet: View {
    @Environment(AppState.self) private var appState
    @Environment(\.dismiss) private var dismiss
    @State private var showFilePicker = false
    @State private var parsedGuests: [Guest] = []
    @State private var rawText = ""
    @State private var detectedPlatform = ""
    @State private var errorMessage: String?
    @State private var tierLimitMessage: String?
    @State private var csvTemplateURL: URL?

    var body: some View {
        NavigationStack {
            ScrollView {
                VStack(alignment: .leading, spacing: 20) {
                    // Header
                    VStack(alignment: .leading, spacing: 8) {
                        Text("Import Guest List")
                            .font(SBFont.displayLarge)
                            .foregroundStyle(Color.sbCharcoal)
                        Text("Import from CSV, Excel, or paste from Joy, Zola, The Knot, and more.")
                            .font(SBFont.bodySmall)
                            .foregroundStyle(Color.sbWarm)
                    }

                    // CSV upload — gold pill button mirroring onboarding's
                    // visual treatment so the two surfaces feel like one
                    // flow.
                    Button {
                        errorMessage = nil
                        showFilePicker = true
                    } label: {
                        HStack(spacing: 10) {
                            Image(systemName: "tray.and.arrow.down")
                                .font(.system(size: 14, weight: .semibold))
                            VStack(alignment: .leading, spacing: 2) {
                                Text("Upload CSV or Excel")
                                    .font(SBFont.bodySemibold)
                                Text("Joy, Zola, The Knot, Eventbrite, generic CSV")
                                    .font(SBFont.caption)
                                    .foregroundStyle(Color.white.opacity(0.85))
                            }
                            Spacer()
                            Image(systemName: "chevron.right")
                                .font(.system(size: 12, weight: .semibold))
                        }
                        .foregroundStyle(Color.white)
                        .padding(14)
                        .background(LinearGradient(colors: [Color.sbGold, Color.sbGoldDk],
                                                   startPoint: .top, endPoint: .bottom))
                        .clipShape(RoundedRectangle(cornerRadius: SBRadius.button))
                    }
                    .buttonStyle(.plain)

                    // Template download — picks wedding / general based
                    // on the active plan's event type. Same template
                    // bytes as onboarding's, generated by GuestCSVParser.
                    if let csvTemplateURL {
                        ShareLink(item: csvTemplateURL) {
                            HStack(spacing: 6) {
                                Image(systemName: "arrow.down.doc")
                                    .font(.system(size: 12, weight: .semibold))
                                Text("Download CSV template")
                                    .font(SBFont.caption)
                            }
                            .foregroundStyle(Color.sbGoldDk)
                        }
                    }

                    SBOrnament(label: "OR PASTE")

                    // Paste area — same plain-text-friendly placeholder
                    // as onboarding so the two surfaces don't disagree
                    // on what's pasteable. Auto-parses on every change.
                    ZStack(alignment: .topLeading) {
                        TextEditor(text: $rawText)
                            .font(SBFont.body)
                            .scrollContentBackground(.hidden)
                            .padding(8)
                            .onChange(of: rawText) { _, _ in parseAuto() }

                        if rawText.isEmpty {
                            Text("Sarah Chen, vegetarian\nJon Park\nAmir Patel, gluten-free\n…")
                                .font(SBFont.body)
                                .foregroundStyle(Color.sbWarm2)
                                .padding(.horizontal, 14)
                                .padding(.vertical, 16)
                                .allowsHitTesting(false)
                        }
                    }
                    .frame(height: 160)
                    .background(Color.sbIvory2)
                    .clipShape(RoundedRectangle(cornerRadius: SBRadius.button))

                    // Inline syntax hint — same copy as onboarding so
                    // discovery of the dietary-after-comma syntax
                    // happens on either surface.
                    HStack(spacing: 4) {
                        Image(systemName: "lightbulb")
                            .font(.system(size: 11))
                            .foregroundStyle(Color.sbGoldDk)
                        Text("Tip: add a comma + dietary note (e.g. \"Sarah Chen, vegetarian\"). Add meals and parties after.")
                            .font(SBFont.caption)
                            .foregroundStyle(Color.sbWarm)
                            .fixedSize(horizontal: false, vertical: true)
                    }

                    // Detected platform
                    if !detectedPlatform.isEmpty && !parsedGuests.isEmpty {
                        HStack(spacing: 8) {
                            Image(systemName: "checkmark.circle.fill")
                                .foregroundStyle(Color.sbSage)
                            Text("Detected: \(detectedPlatform)")
                                .font(SBFont.bodySemibold)
                                .foregroundStyle(Color.sbCharcoal)
                        }
                    }

                    // Error
                    if let errorMessage {
                        Text(errorMessage)
                            .font(SBFont.caption)
                            .foregroundStyle(Color.sbError)
                    }

                    // Preview
                    if !parsedGuests.isEmpty {
                        VStack(alignment: .leading, spacing: 12) {
                            Text("\(parsedGuests.count) GUESTS FOUND")
                                .font(SBFont.capsLabel)
                                .foregroundStyle(Color.sbGoldDk)
                                .letterSpacing(1.5)

                            ForEach(parsedGuests.prefix(10)) { guest in
                                HStack(spacing: 10) {
                                    SBAvatar(name: guest.displayName, size: 28)
                                    VStack(alignment: .leading, spacing: 1) {
                                        Text(guest.displayName)
                                            .font(SBFont.bodySmallBold)
                                            .foregroundStyle(Color.sbCharcoal)
                                        if let dietary = guest.dietary {
                                            Text(dietary)
                                                .font(SBFont.caption)
                                                .foregroundStyle(Color.sbWarm)
                                        }
                                    }
                                    Spacer()
                                    if guest.side != .none {
                                        SBChip(text: guest.side.rawValue.capitalized, variant: .gold)
                                    }
                                }
                            }

                            if parsedGuests.count > 10 {
                                Text("+ \(parsedGuests.count - 10) more")
                                    .font(SBFont.caption)
                                    .foregroundStyle(Color.sbWarm)
                            }
                        }

                        SBButton(title: "Import \(parsedGuests.count) guests", icon: "person.badge.plus", variant: .gold, fullWidth: true) {
                            importGuests()
                        }
                    }

                    Spacer(minLength: 40)
                }
                .padding(.horizontal, SBSpacing.screenMargin)
                .padding(.top, 16)
            }
            .background(Color.sbIvory)
            .navigationTitle("Import")
            .navigationBarTitleDisplayMode(.inline)
            .task {
                // Build the right CSV template for this plan's event
                // type. Wedding by default for plans with no type.
                let evt = appState.activePlan?.eventType
                let templateType: GuestCSVParser.TemplateType =
                    (evt == .wedding) ? .wedding : .general
                csvTemplateURL = GuestCSVParser.writeCSVTemplate(for: templateType)
            }
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel") { dismiss() }
                        .foregroundStyle(Color.sbWarm)
                }
            }
            .fileImporter(isPresented: $showFilePicker, allowedContentTypes: [.commaSeparatedText, .plainText, .data]) { result in
                switch result {
                case .success(let url):
                    loadFile(url)
                case .failure(let error):
                    errorMessage = error.localizedDescription
                }
            }
            .alert(
                "Guest Limit Reached",
                isPresented: Binding(get: { tierLimitMessage != nil }, set: { if !$0 { tierLimitMessage = nil } })
            ) {
                Button("Upgrade") { appState.showUpgrade = true }
                Button("Not now", role: .cancel) {}
            } message: {
                Text(tierLimitMessage ?? "")
            }
        }
    }

    // MARK: - File Loading

    private func loadFile(_ url: URL) {
        guard url.startAccessingSecurityScopedResource() else {
            errorMessage = "Can't access file"
            return
        }
        defer { url.stopAccessingSecurityScopedResource() }

        do {
            let text = try String(contentsOf: url, encoding: .utf8)
            rawText = text
            // The .onChange on the TextEditor handles auto-parsing,
            // but file uploads bypass that path — explicit call here.
            parseAuto()
        } catch {
            errorMessage = "Failed to read file: \(error.localizedDescription)"
        }
    }

    // MARK: - Parsing
    //
    // Same shared helper as the onboarding paste textarea so paste +
    // file flows produce identical Guest objects regardless of which
    // surface the user came in on. Header-row CSV uses the full
    // platform-detecting parser; plain-text-per-line goes through
    // the lightweight "Name, dietary" path.

    private func parseAuto() {
        let result = GuestCSVParser.parseFlexible(rawText)
        parsedGuests = result.guests
        detectedPlatform = result.guests.isEmpty ? "" : result.detectedPlatform
        // Only surface "no guests" errors when there's actual input —
        // an empty textarea isn't an error state.
        errorMessage = rawText.isEmpty ? nil : result.error
    }

    // MARK: - Import

    private func importGuests() {
        guard var plan = appState.activePlan else { return }

        // Web parity: importing guests is never blocked by the tier limit.
        // The limit only applies when SEATING guests (assigning to tables).
        // Users should be able to build their full guest list on the free
        // tier and only hit the gate when they try to seat more than the cap.
        plan.guests.append(contentsOf: parsedGuests)
        appState.activePlan = plan
        HapticEngine.success()

        Task {
            try? await appState.database.savePlanData(plan: plan)
        }

        dismiss()
    }
}

private extension String {
    var nilIfEmpty: String? {
        trimmingCharacters(in: .whitespaces).isEmpty ? nil : self
    }
}

#Preview {
    CSVImportSheet()
        .environment(AppState())
}
