import Foundation

// SampleEventService — loads the bundled SampleEvent.json (generated by
// scripts/generate-sample-event.mjs) and hands back a fully-formed
// SeatingPlan with `isDemo = true`, plus a pre-baked SeatService.GenerateResult
// so the AI button can play it back without ever calling /api/seat.
//
// Demo plans are LOCAL ONLY. They never round-trip through Supabase. Every
// service that could leak cost (AI, image upload, share-link mint, save) must
// early-return on `plan.isDemo`. SampleEventService is the only place where
// the demo plan is materialized.
//
// The bundled JSON shape is documented in scripts/generate-sample-event.mjs.

final class SampleEventService {
    static let shared = SampleEventService()
    private init() {}

    /// Stable ID baked into the JSON. Anywhere in the app that needs to ask
    /// "is this the sample plan?" without dereferencing isDemo can compare
    /// against this constant — useful for early-return guards in services
    /// that take an `id: String` rather than a SeatingPlan.
    static let samplePlanId = "demo-sample-event"

    enum SampleError: LocalizedError {
        case bundleResourceMissing
        case decodeFailed(String)

        var errorDescription: String? {
            switch self {
            case .bundleResourceMissing: return "SampleEvent.json missing from app bundle"
            case .decodeFailed(let m):   return "Failed to decode SampleEvent.json: \(m)"
            }
        }
    }

    /// Cached on first load. Sample data is small (~250 KB) but parsing it
    /// every time the user toggles tabs is wasteful, and it never changes
    /// at runtime.
    private var cached: (plan: SeatingPlan, preBakedResult: SeatService.GenerateResult)?

    /// Returns the demo plan + the pre-baked AI playback result.
    func load() throws -> (plan: SeatingPlan, preBakedResult: SeatService.GenerateResult) {
        if let cached { return cached }

        guard let url = Bundle.main.url(forResource: "SampleEvent", withExtension: "json") else {
            throw SampleError.bundleResourceMissing
        }
        let data = try Data(contentsOf: url)

        let envelope: SampleEnvelope
        do {
            envelope = try JSONDecoder().decode(SampleEnvelope.self, from: data)
        } catch {
            throw SampleError.decodeFailed(error.localizedDescription)
        }

        let plan = envelope.toSeatingPlan()
        let preBakedResult = envelope.toGenerateResult()
        cached = (plan, preBakedResult)
        return (plan, preBakedResult)
    }

    /// Convenience: just the plan, hydrating fresh state every call so users
    /// can "reset" the demo by re-loading without restarting the app.
    func freshPlan() throws -> SeatingPlan {
        // Clear cache so reset is true reset.
        cached = nil
        let result = try load()
        return result.plan
    }

    /// Convenience: just the pre-baked AI result. Used by SeatService when
    /// the active plan is the demo and the user taps "AI seat".
    func preBakedResult() throws -> SeatService.GenerateResult {
        let result = try load()
        return result.preBakedResult
    }
}

// MARK: - Bundled JSON envelope

/// Top-level shape of SampleEvent.json. See scripts/generate-sample-event.mjs.
private struct SampleEnvelope: Decodable {
    let schemaVersion: Int
    let plan: SamplePlan
    let preBakedAI: SamplePreBakedAI

    func toSeatingPlan() -> SeatingPlan {
        plan.toDomain()
    }

    func toGenerateResult() -> SeatService.GenerateResult {
        preBakedAI.toGenerateResult()
    }
}

private struct SamplePlan: Decodable {
    let id: String
    let name: String
    let eventDate: String?
    let venue: String?
    let eventType: String
    let isDemo: Bool
    let roomWidth: Double?
    let roomHeight: Double?
    let roomShape: String?
    let measurementUnit: String?
    let hasSweetheartTable: Bool?
    let coupleType: String?
    let tables: [SampleTable]
    let guests: [SampleGuest]
    let rules: [SampleRule]
    let objects: [SampleObject]
    let categories: [[String: AnyJSONValue]]?
    let parties: [SampleParty]?

    func toDomain() -> SeatingPlan {
        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "yyyy-MM-dd"
        let parsedDate = eventDate.flatMap { dateFormatter.date(from: $0) }

        return SeatingPlan(
            id: id,
            name: name,
            eventDate: parsedDate,
            venue: venue,
            eventType: SeatingPlan.EventType(rawValue: eventType) ?? .wedding,
            tables: tables.map { $0.toDomain() },
            guests: guests.map { $0.toDomain() },
            rules: rules.map { $0.toDomain() },
            objects: objects.map { $0.toDomain() },
            roomWidth: roomWidth,
            roomHeight: roomHeight,
            roomShape: roomShape,
            measurementUnit: measurementUnit,
            customRoomPoints: nil,
            roomFlipH: nil,
            roomFlipV: nil,
            roomZones: nil,
            hasSweetheartTable: hasSweetheartTable,
            includeMaybes: nil,
            coupleType: coupleType,
            createdAt: nil,
            updatedAt: nil,
            userId: nil,
            tier: "event_pass",  // demo plan is treated as event-pass-equivalent
            eventPassExpiresAt: Calendar.current.date(byAdding: .year, value: 10, to: Date()),
            eventPassPurchasedAt: nil,
            isDemo: isDemo,
            rawCategories: categories?.map { dict in
                dict.mapValues { AnyCodable($0.unwrapped) }
            },
            rawParties: parties?.map { p in
                [
                    "id":       AnyCodable(p.id),
                    "name":     AnyCodable(p.name),
                    "guestIds": AnyCodable(p.guestIds),
                ]
            },
            rawGroups: nil,
            rawFloorPlanImage: nil,
            rawFloorPlanOpacity: nil,
            rawSeatOrders: nil,
            rawGuestQR: nil
        )
    }
}

private struct SampleTable: Decodable {
    let id: String
    let name: String
    let type: String
    let seats: Int
    let x: Double
    let y: Double
    let width: Double?
    let height: Double?
    let diameter: Double?
    let sweetShape: String?
    let oneSide: Bool?
    let color: String?
    let assignments: [String: Int]?

    func toDomain() -> SeatTable {
        SeatTable(
            id: id,
            name: name,
            type: SeatTable.TableType(rawValue: type) ?? .round,
            seats: seats,
            x: x,
            y: y,
            rotation: nil,
            assignments: assignments ?? [:],
            locked: nil,
            color: color,
            width: width,
            height: height,
            diameter: diameter,
            sweetShape: sweetShape,
            oneSide: oneSide,
            notes: nil
        )
    }
}

private struct SampleGuest: Decodable {
    let id: String
    let firstName: String?
    let lastName: String?
    let name: String
    let display: String?
    let side: String
    let vip: Bool
    let rsvp: String
    let party: String?
    let meal: String?
    let categories: [String]?
    let dietaryTags: [String]?
    let plusOne: Bool?
    let isChild: Bool?
    let isBride: Bool?
    let isGroom: Bool?

    func toDomain() -> Guest {
        Guest(
            id: id,
            name: name,
            firstName: firstName,
            lastName: lastName,
            email: nil,
            categories: categories ?? [],
            dietary: nil,
            notes: nil,
            rsvp: Guest.RSVPStatus(rawValue: rsvp) ?? .yes,
            side: Guest.GuestSide(rawValue: side) ?? .none,
            vip: vip,
            accessibility: nil,
            plusOne: plusOne,
            party: party,
            display: display,
            dietaryTags: dietaryTags,
            highChair: nil,
            isChild: isChild,
            groupIds: nil,
            isBride: isBride,
            isGroom: isGroom,
            meal: meal,
            guestCreatedAt: nil
        )
    }
}

private struct SampleRule: Decodable {
    let id: String
    let type: String
    let guests: [String]
    let weight: Int
    let hard: Bool
    let enabled: Bool
    let desc: String?
    let partyId: String?
    // Type-specific anchors. Without these, edit-mode opens with no
    // category/object/table selected (the field reads nil from the
    // hydrated rule even though the JSON contains the value), and the
    // Save button stays disabled because canSubmit fails its required-
    // anchor check. Decoded as optionals so older/simpler rules still
    // round-trip cleanly.
    let categoryId: String?
    let objectId: String?
    let tableId: String?
    let sideValue: String?
    let sideA: [String]?
    let sideB: [String]?

    func toDomain() -> SeatingRule {
        SeatingRule(
            id: id,
            type: SeatingRule.RuleType.parse(type),
            guests: guests,
            tableId: tableId,
            weight: weight,
            hard: hard,
            enabled: enabled,
            categoryId: categoryId,
            objectId: objectId,
            sideValue: sideValue,
            sideA: sideA,
            sideB: sideB,
            desc: desc,
            auto: nil,
            source: nil,
            partyId: partyId,
            groupId: nil
        )
    }
}

private struct SampleObject: Decodable {
    let id: String
    let type: String
    let name: String
    let x: Double
    let y: Double
    let width: Double
    let height: Double
    let color: String?
    let category: String?
    let isObstacle: Bool?

    func toDomain() -> RoomObject {
        RoomObject(
            id: id, type: type, name: name,
            x: x, y: y, width: width, height: height,
            rotation: nil, color: color, category: category, icon: nil,
            isObstacle: isObstacle, locked: nil
        )
    }
}

private struct SampleParty: Decodable {
    let id: String
    let name: String
    let guestIds: [String]
}

// MARK: - Pre-baked AI playback

private struct SamplePreBakedAI: Decodable {
    // Whole blob captured as raw JSON values. Earlier versions tried to
    // decode each field into typed properties and rebuilt the scorecard
    // dict by hand — that lossily dropped the per-rule satisfaction
    // arrays (hardConstraints.rules / softPreferences.rules), so the
    // demo run page never showed the rule-by-rule breakdown the real
    // AI flow surfaces. Now we just round-trip the whole blob and let
    // SeatService.GenerateResult's existing custom decoder pick it
    // apart — every field including suggestions and rule entries
    // survives unchanged.
    let raw: AnyJSONValue

    init(from decoder: Decoder) throws {
        raw = try AnyJSONValue(from: decoder)
    }

    func toGenerateResult() -> SeatService.GenerateResult {
        let unwrapped = raw.unwrapped
        do {
            let data = try JSONSerialization.data(withJSONObject: unwrapped, options: [])
            return try JSONDecoder().decode(SeatService.GenerateResult.self, from: data)
        } catch {
            // Fail loud rather than silently hand back an empty result —
            // a broken pre-bake is a build-time bug, not a runtime one,
            // and we want it surfaced immediately during dev.
            assertionFailure("SampleEvent preBakedAI decode failed: \(error)")
            return SeatService.GenerateResult.empty
        }
    }
}

// MARK: - Lenient JSON value
//
// SampleEvent.json contains a few heterogeneous blobs (categories,
// seatOrders) where we don't want to type out the full schema for the
// demo. AnyJSONValue accepts whatever JSON throws at it and exposes
// the underlying value via `.unwrapped`.

private enum AnyJSONValue: Decodable {
    case string(String)
    case int(Int)
    case double(Double)
    case bool(Bool)
    case array([AnyJSONValue])
    case dictionary([String: AnyJSONValue])
    case null

    init(from decoder: Decoder) throws {
        let c = try decoder.singleValueContainer()
        if c.decodeNil() { self = .null }
        else if let v = try? c.decode(Bool.self) { self = .bool(v) }
        else if let v = try? c.decode(Int.self) { self = .int(v) }
        else if let v = try? c.decode(Double.self) { self = .double(v) }
        else if let v = try? c.decode(String.self) { self = .string(v) }
        else if let v = try? c.decode([AnyJSONValue].self) { self = .array(v) }
        else if let v = try? c.decode([String: AnyJSONValue].self) { self = .dictionary(v) }
        else { self = .null }
    }

    var unwrapped: Any {
        switch self {
        case .string(let s):     return s
        case .int(let i):        return i
        case .double(let d):     return d
        case .bool(let b):       return b
        case .array(let a):      return a.map { $0.unwrapped }
        case .dictionary(let d): return d.mapValues { $0.unwrapped }
        case .null:              return NSNull()
        }
    }
}

// MARK: - SeatService.GenerateResult convenience

extension SeatService.GenerateResult {
    /// Empty result used as a graceful fallback if pre-baked decode somehow
    /// fails. Tapping AI just returns no-op rather than crashing.
    static var empty: SeatService.GenerateResult {
        let json = """
        {"assignments":{},"seatOrders":{},"score":0,"fallback":false,
         "scorecard":{"overallPercent":0,"overallLabel":"N/A","totalRules":0,"totalSatisfied":0,
         "hardConstraints":{"total":0,"satisfied":0,"partial":0,"violated":0,"rules":[]},
         "softPreferences":{"total":0,"satisfied":0,"partial":0,"violated":0,"rules":[]},
         "suggestions":[]}}
        """.data(using: .utf8)!
        return (try? JSONDecoder().decode(SeatService.GenerateResult.self, from: json))
            ?? unsafeBitCast(0, to: SeatService.GenerateResult.self)  // unreachable
    }
}
